In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
d = pd.read_csv(r"E:\SmartInternz\SmartBridgeTraining\bank (1).csv")

In [4]:
d.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [5]:
d.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [6]:
d.shape

(11162, 17)

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
d["deposit"]= le.fit_transform(d["deposit"])


In [8]:
d.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome  deposit  
0    5   may      1042         1     -1         0  unknown        1

In [11]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
age          11162 non-null int64
job          11162 non-null object
marital      11162 non-null object
education    11162 non-null object
default      11162 non-null object
balance      11162 non-null int64
housing      11162 non-null object
loan         11162 non-null object
contact      11162 non-null object
day          11162 non-null int64
month        11162 non-null object
duration     11162 non-null int64
campaign     11162 non-null int64
pdays        11162 non-null int64
previous     11162 non-null int64
poutcome     11162 non-null object
deposit      11162 non-null int32
dtypes: int32(1), int64(7), object(9)
memory usage: 1.4+ MB


In [14]:
d.loan.unique()

array(['no', 'yes'], dtype=object)

In [175]:
from collections import Counter as c
c(d.deposit)

Counter({1: 5289, 0: 5873})

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
d.loan=le.fit_transform(d.loan)

In [18]:
d.head(1)

age     job  marital  education default  balance housing  loan  contact  \
0   59  admin.  married  secondary      no     2343     yes     0  unknown   

   day month  duration  campaign  pdays  previous poutcome  deposit  
0    5   may      1042         1     -1         0  unknown        1

In [190]:
x=d.iloc[:,[0,5,9,11,12,13,14]]

In [191]:
x

age  balance  day  duration  campaign  pdays  previous
0       59     2343    5      1042         1     -1         0
1       56       45    5      1467         1     -1         0
2       41     1270    5      1389         1     -1         0
3       55     2476    5       579         1     -1         0
4       54      184    5       673         2     -1         0
5       42        0    5       562         2     -1         0
6       56      830    6      1201         1     -1         0
7       60      545    6      1030         1     -1         0
8       37        1    6       608         1     -1         0
9       28     5090    6      1297         3     -1         0
10      38      100    7       786         1     -1         0
11      30      309    7      1574         2     -1         0
12      29      199    7      1689         4     -1         0
13      46      460    7      1102         2     -1         0
14      31      703    8       943         2     -1         0
15      35     3837    8      1084         1     -1         0
16      32      611    8       541         3     -1         0
17      49       -8    8      1119         1     -1         0
18      41       55    8      1120         2     -1         0
19      49      168    8       513         1     -1         0
20      28      785    8       442         2     -1         0
21      43     2067    8       756         1     -1         0
22      43      388    8      2087         2     -1         0
23      43     -192    8      1120         2     -1         0
24      37      381    8       985         2     -1         0
25      35       40    9       617         4     -1         0
26      31       22    9       483         3     -1         0
27      43        3    9       929         3     -1         0
28      31      307    9       538         1     -1         0
29      28      759    9       710         1     -1         0
...    ...      ...  ...       ...       ...    ...       ...
11132   32     -325   21       171         1     -1         0
11133   37     1594   17       110         1    260         5
11134   58     2596   18        15         2     -1         0
11135   36      115    6       201         1     -1         0
11136   31        0    8        76         1     -1         0
11137   49      247   15       213         2     -1         0
11138   32      235   28       688         6     -1         0
11139   30     2593   27       662         7     -1         0
11140   55     2166   28        23        17     -1         0
11141   32      130    6       302         2     -1         0
11142   52       48   17       591         1     -1         0
11143   38      189   21       105         2     -1         0
11144   60        0   15       229         1     -1         0
11145   60     -134   12       243         1    271         4
11146   30       23    4       149         2     -1         0
11147   44        0   21       175         4     -1         0
11148   32        1    8       102         1     -1         0
11149   46     3317   19       231         2     -1         0
11150   34      355   21       314         3     -1         0
11151   40      917   20       292         1     -1         0
11152   34      390   15       659         3     -1         0
11153   43       35    9       208         1     -1         0
11154   52      523    8       113         1     -1         0
11155   35       80   21        38         2    172         2
11156   34      -72    7       273         5     -1         0
11157   33        1   20       257         1     -1         0
11158   39      733   16        83         4     -1         0
11159   32       29   19       156         2     -1         0
11160   43        0    8         9         2    172         5
11161   34        0    9       628         1     -1         0

[11162 rows x 7 columns]

In [192]:
y=d.iloc[:,16]

In [193]:
y

0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
        ..
11132    0
11133    0
11134    0
11135    0
11136    0
11137    0
11138    0
11139    0
11140    0
11141    0
11142    0
11143    0
11144    0
11145    0
11146    0
11147    0
11148    0
11149    0
11150    0
11151    0
11152    0
11153    0
11154    0
11155    0
11156    0
11157    0
11158    0
11159    0
11160    0
11161    0
Name: deposit, Length: 11162, dtype: int32

In [194]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state =10)

In [195]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [196]:
x_test

array([[ 0.30355616, -0.40717069,  1.71499908, ...,  0.61540723,
        -0.479803  , -0.38004742],
       [-0.77978927, -0.33049416,  0.40410683, ..., -0.5802462 ,
        -0.479803  , -0.38004742],
       [ 2.38691275, -0.38641111,  1.47665503, ..., -0.18169506,
        -0.479803  , -0.38004742],
       ...,
       [ 0.13688763,  0.20356285,  1.11913897, ..., -0.18169506,
         0.38154486,  1.4294321 ],
       [-0.11311516, -0.29198849, -0.78761339, ..., -0.5802462 ,
        -0.479803  , -0.38004742],
       [-1.11312632, -0.24511201,  0.04659076, ..., -0.5802462 ,
        -0.479803  , -0.38004742]])

In [197]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train,y_train)

C:\Users\ser\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [198]:
ypred = logreg.predict(x_test)

In [199]:
ypred

array([1, 0, 0, ..., 1, 1, 0])

In [200]:
y_test

10794    0
988      1
8515     0
10223    0
10052    0
4976     1
2643     1
1998     1
9309     0
2261     1
4305     1
43       1
8038     0
3668     1
6140     0
3627     1
7040     0
4112     1
5948     0
2037     1
2241     1
9307     0
10029    0
9100     0
5811     0
923      1
4871     1
8877     0
1356     1
9603     0
        ..
2303     1
4131     1
2574     1
7518     0
4717     1
8729     0
10109    0
10289    0
5527     0
10967    0
2634     1
529      1
8265     0
774      1
1051     1
1796     1
1724     1
9278     0
6580     0
2680     1
3675     1
10787    0
2922     1
1836     1
1582     1
6411     0
5880     0
2594     1
401      1
1253     1
Name: deposit, Length: 2233, dtype: int32

In [201]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(ypred,y_test)

In [202]:
accuracy

0.7523510971786834

In [203]:
d.head(20)

age          job   marital  education default  balance housing  loan  \
0    59       admin.   married  secondary      no     2343     yes     0   
1    56       admin.   married  secondary      no       45      no     0   
2    41   technician   married  secondary      no     1270     yes     0   
3    55     services   married  secondary      no     2476     yes     0   
4    54       admin.   married   tertiary      no      184      no     0   
5    42   management    single   tertiary      no        0     yes     1   
6    56   management   married   tertiary      no      830     yes     1   
7    60      retired  divorced  secondary      no      545     yes     0   
8    37   technician   married  secondary      no        1     yes     0   
9    28     services    single  secondary      no     5090     yes     0   
10   38       admin.    single  secondary      no      100     yes     0   
11   30  blue-collar   married  secondary      no      309     yes     0   
12   29   management   married   tertiary      no      199     yes     1   
13   46  blue-collar    single   tertiary      no      460     yes     0   
14   31   technician    single   tertiary      no      703     yes     0   
15   35   management  divorced   tertiary      no     3837     yes     0   
16   32  blue-collar    single    primary      no      611     yes     0   
17   49     services   married  secondary      no       -8     yes     0   
18   41       admin.   married  secondary      no       55     yes     0   
19   49       admin.  divorced  secondary      no      168     yes     1   

    contact  day month  duration  campaign  pdays  previous poutcome  deposit  
0   unknown    5   may      1042         1     -1         0  unknown        1  
1   unknown    5   may      1467         1     -1         0  unknown        1  
2   unknown    5   may      1389         1     -1         0  unknown        1  
3   unknown    5   may       579         1     -1         0  unknown        1  
4   unknown    5   may       673         2     -1         0  unknown        1  
5   unknown    5   may       562         2     -1         0  unknown        1  
6   unknown    6   may      1201         1     -1         0  unknown        1  
7   unknown    6   may      1030         1     -1         0  unknown        1  
8   unknown    6   may       608         1     -1         0  unknown        1  
9   unknown    6   may      1297         3     -1         0  unknown        1  
10  unknown    7   may       786         1     -1         0  unknown        1  
11  unknown    7   may      1574         2     -1         0  unknown        1  
12  unknown    7   may      1689         4     -1         0  unknown        1  
13  unknown    7   may      1102         2     -1         0  unknown        1  
14  unknown    8   may       943         2     -1         0  unknown        1  
15  unknown    8   may      1084         1     -1         0  unknown        1  
16  unknown    8   may       541         3     -1         0  unknown        1  
17  unknown    8   may      1119         1     -1         0  unknown        1  
18  unknown    8   may      1120         2     -1         0  unknown        1  
19  unknown    8   may       513         1     -1         0  unknown        1

In [204]:
logreg.predict(sc.transform([[41,55,8,1120,2,-1,0]]))

array([1])

In [205]:
logreg.predict(sc.transform([[28,3,18,40,8,349,6]]))

array([0])