In [1]:
import numpy as np
import pandas as pd

In [2]:
d =pd.read_csv(r"E:\SmartInternz\SmartBridgeTraining\Fish.csv")

In [3]:
d.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [4]:
d.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [5]:
d["Species"].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [6]:
x=d.iloc[:,0:6]

In [7]:
y=d.iloc[:,6]

In [8]:
x

Species  Weight  Length1  Length2  Length3   Height
0     Bream   242.0     23.2     25.4     30.0  11.5200
1     Bream   290.0     24.0     26.3     31.2  12.4800
2     Bream   340.0     23.9     26.5     31.1  12.3778
3     Bream   363.0     26.3     29.0     33.5  12.7300
4     Bream   430.0     26.5     29.0     34.0  12.4440
5     Bream   450.0     26.8     29.7     34.7  13.6024
6     Bream   500.0     26.8     29.7     34.5  14.1795
7     Bream   390.0     27.6     30.0     35.0  12.6700
8     Bream   450.0     27.6     30.0     35.1  14.0049
9     Bream   500.0     28.5     30.7     36.2  14.2266
10    Bream   475.0     28.4     31.0     36.2  14.2628
11    Bream   500.0     28.7     31.0     36.2  14.3714
12    Bream   500.0     29.1     31.5     36.4  13.7592
13    Bream   340.0     29.5     32.0     37.3  13.9129
14    Bream   600.0     29.4     32.0     37.2  14.9544
15    Bream   600.0     29.4     32.0     37.2  15.4380
16    Bream   700.0     30.4     33.0     38.3  14.8604
17    Bream   700.0     30.4     33.0     38.5  14.9380
18    Bream   610.0     30.9     33.5     38.6  15.6330
19    Bream   650.0     31.0     33.5     38.7  14.4738
20    Bream   575.0     31.3     34.0     39.5  15.1285
21    Bream   685.0     31.4     34.0     39.2  15.9936
22    Bream   620.0     31.5     34.5     39.7  15.5227
23    Bream   680.0     31.8     35.0     40.6  15.4686
24    Bream   700.0     31.9     35.0     40.5  16.2405
25    Bream   725.0     31.8     35.0     40.9  16.3600
26    Bream   720.0     32.0     35.0     40.6  16.3618
27    Bream   714.0     32.7     36.0     41.5  16.5170
28    Bream   850.0     32.8     36.0     41.6  16.8896
29    Bream  1000.0     33.5     37.0     42.6  18.9570
..      ...     ...      ...      ...      ...      ...
129    Pike   300.0     31.7     34.0     37.8   5.7078
130    Pike   300.0     32.7     35.0     38.8   5.9364
131    Pike   300.0     34.8     37.3     39.8   6.2884
132    Pike   430.0     35.5     38.0     40.5   7.2900
133    Pike   345.0     36.0     38.5     41.0   6.3960
134    Pike   456.0     40.0     42.5     45.5   7.2800
135    Pike   510.0     40.0     42.5     45.5   6.8250
136    Pike   540.0     40.1     43.0     45.8   7.7860
137    Pike   500.0     42.0     45.0     48.0   6.9600
138    Pike   567.0     43.2     46.0     48.7   7.7920
139    Pike   770.0     44.8     48.0     51.2   7.6800
140    Pike   950.0     48.3     51.7     55.1   8.9262
141    Pike  1250.0     52.0     56.0     59.7  10.6863
142    Pike  1600.0     56.0     60.0     64.0   9.6000
143    Pike  1550.0     56.0     60.0     64.0   9.6000
144    Pike  1650.0     59.0     63.4     68.0  10.8120
145   Smelt     6.7      9.3      9.8     10.8   1.7388
146   Smelt     7.5     10.0     10.5     11.6   1.9720
147   Smelt     7.0     10.1     10.6     11.6   1.7284
148   Smelt     9.7     10.4     11.0     12.0   2.1960
149   Smelt     9.8     10.7     11.2     12.4   2.0832
150   Smelt     8.7     10.8     11.3     12.6   1.9782
151   Smelt    10.0     11.3     11.8     13.1   2.2139
152   Smelt     9.9     11.3     11.8     13.1   2.2139
153   Smelt     9.8     11.4     12.0     13.2   2.2044
154   Smelt    12.2     11.5     12.2     13.4   2.0904
155   Smelt    13.4     11.7     12.4     13.5   2.4300
156   Smelt    12.2     12.1     13.0     13.8   2.2770
157   Smelt    19.7     13.2     14.3     15.2   2.8728
158   Smelt    19.9     13.8     15.0     16.2   2.9322

[159 rows x 6 columns]

In [9]:
x.shape

(159, 6)

In [10]:
y

0      4.0200
1      4.3056
2      4.6961
3      4.4555
4      5.1340
5      4.9274
6      5.2785
7      4.6900
8      4.8438
9      4.9594
10     5.1042
11     4.8146
12     4.3680
13     5.0728
14     5.1708
15     5.5800
16     5.2854
17     5.1975
18     5.1338
19     5.7276
20     5.5695
21     5.3704
22     5.2801
23     6.1306
24     5.5890
25     6.0532
26     6.0900
27     5.8515
28     6.1984
29     6.6030
        ...  
129    4.1580
130    4.3844
131    4.0198
132    4.5765
133    3.9770
134    4.3225
135    4.4590
136    5.1296
137    4.8960
138    4.8700
139    5.3760
140    6.1712
141    6.9849
142    6.1440
143    6.1440
144    7.4800
145    1.0476
146    1.1600
147    1.1484
148    1.3800
149    1.2772
150    1.2852
151    1.2838
152    1.1659
153    1.1484
154    1.3936
155    1.2690
156    1.2558
157    2.0672
158    1.8792
Name: Width, Length: 159, dtype: float64

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder = "passthrough")
x = ct.fit_transform(x)

In [15]:
x[1]

array([  1.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  , 290.  ,
        24.  ,  26.3 ,  31.2 ,  12.48])

In [14]:
x.shape

(159, 12)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state =1)

In [17]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
ypred =  mlr.predict(x_test)

In [19]:
ypred

array([7.02002109, 3.39337557, 5.30963612, 3.68279772, 3.21262065,
       5.26874455, 3.57979568, 5.05218485, 3.39055824, 3.94507944,
       3.66070597, 3.51348164, 2.36430948, 4.46015914, 6.41404038,
       3.53854175, 3.0817733 , 5.24968227, 4.76113121, 4.09581124,
       1.37853398, 2.26468956, 3.97836375, 4.63293386, 3.53865173,
       6.79844216, 5.38672484, 1.07489983, 6.91625863, 3.73114186,
       7.48603375, 4.42615913])

In [20]:
y_test

29     6.6030
42     3.2943
14     5.1708
91     3.6240
81     2.7720
19     5.7276
44     3.5478
11     4.8146
40     3.3516
97     3.8250
89     3.5250
94     3.6260
73     1.9992
105    4.5662
59     6.5736
90     3.9950
66     3.2944
54     5.3550
108    4.7716
100    4.2390
153    1.1484
35     2.2680
51     3.9060
5      4.9274
84     3.6675
31     6.2920
16     5.2854
145    1.0476
143    6.1440
93     3.6300
127    7.5958
103    4.3350
Name: Width, dtype: float64

In [21]:
x_test

array([[1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 1.00000e+03, 3.35000e+01, 3.70000e+01,
        4.26000e+01, 1.89570e+01],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
        0.00000e+00, 0.00000e+00, 1.20000e+02, 1.94000e+01, 2.10000e+01,
        2.37000e+01, 6.11460e+00],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 6.00000e+02, 2.94000e+01, 3.20000e+01,
        3.72000e+01, 1.49544e+01],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 1.30000e+02, 2.05000e+01, 2.25000e+01,
        2.40000e+01, 5.85600e+00],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 8.50000e+01, 1.82000e+01, 2.00000e+01,
        2.10000e+01, 5.08200e+00],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0

In [22]:
from sklearn.metrics import r2_score
accuracy = r2_score(ypred,y_test)

In [23]:
accuracy

0.9702558575118931

In [24]:
d.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [26]:
a=[["Bream",363.0,26.3,29.0,33.5,12.7300]]

In [27]:
b=ct.transform(a)

In [28]:
b

array([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 363.0, 26.3, 29.0, 33.5,
        12.73]], dtype=object)

In [32]:
yp=mlr.predict(b)

In [33]:
yp

array([4.22460328])